name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .npmrc file for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_PACKAGES }}" > .npmrc
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com" >> .npmrc

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest --secret id=npmrc,src=${{ github.workspace }}/.npmrc

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - uses: actions/delete-package-versions@v5
        with:
          package-name: "${{ github.event.repository.name }}"
          package-type: "container"
          delete-only-untagged-versions: "true"
